import type { FoundryStatus } from "../types/cockpit";
import { navGroups, pageRegistry, type PageKey } from "../navigation";
export type { PageKey } from "../navigation";

interface SidebarProps { current: PageKey; onNavigate: (page: PageKey) => void; attentionCount: number; syncBadge: number; risksBadge: number; foundryStatus?: FoundryStatus; nextSessionLabel: string; }
export function Sidebar({ current, onNavigate, attentionCount, syncBadge, risksBadge, foundryStatus, nextSessionLabel }: SidebarProps) {
  const badges = { attention: attentionCount, sync: syncBadge, risks: risksBadge }; const configured = foundryStatus?.state === "configured";
  return <nav className="sidebar" aria-label="Dashboard navigation"><div className="sidebar-brand"><div className="sidebar-brand-mark" /><span className="sidebar-brand-name">Kaihou</span></div>{Object.entries(pageRegistry).filter(([, entry]) => entry.nav && !entry.nav.group).map(([key, entry]) => <button key={key} className={`sidebar-item${current === key ? " active" : ""}`} onClick={() => onNavigate(key as PageKey)}><span>{entry.nav!.label}</span>{entry.nav!.badge && badges[entry.nav!.badge] > 0 && <span className="sidebar-badge sidebar-badge--attention">{badges[entry.nav!.badge]}</span>}</button>)}{navGroups.map((group) => <div key={group.key}><div className="sidebar-group-label">{group.label}</div>{Object.entries(pageRegistry).filter(([, entry]) => entry.nav?.group === group.key).sort(([, left], [, right]) => (left.nav!.order ?? 0) - (right.nav!.order ?? 0)).map(([key, entry]) => { const active = current === key || entry.nav!.aliases?.includes(current); const badge = entry.nav!.badge ? badges[entry.nav!.badge] : 0; return <button key={key} className={`sidebar-item${active ? " active" : ""}`} onClick={() => onNavigate(key as PageKey)}><span>{entry.nav!.label}</span>{entry.mode === "overlay" && <span className="sidebar-overlay-glyph">⇥</span>}{badge > 0 && <span className="sidebar-badge sidebar-badge--info">{badge}</span>}</button>; })}</div>)}<div className="sidebar-footer"><div className="sidebar-foundry"><span className={`sidebar-foundry-dot sidebar-foundry-dot--${configured ? "on" : "off"}`} />Foundry · {configured ? "configured" : "not configured"}</div><button className="sidebar-session-cta" onClick={() => onNavigate("run-mode")}><span className="sidebar-session-cta-label">{nextSessionLabel}</span><span className="sidebar-session-cta-action">RUN →</span></button></div></nav>;
}
