-- Migration: Create scenes table for Quick Scene Builder
-- Stores structured scene metadata and links to vault markdown files

CREATE TABLE IF NOT EXISTS scenes (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  type TEXT,
  cuttable BOOLEAN DEFAULT FALSE,
  purpose TEXT,
  pc_pressure TEXT,
  entry_pressure TEXT,
  exit_condition TEXT,
  cast_list TEXT,
  location TEXT,
  clock_thread TEXT,
  core_clue TEXT,
  superior_clue TEXT,
  optional_clue TEXT,
  false_lead TEXT,
  opening_image TEXT,
  sensory_words TEXT,
  interactable_objects TEXT,
  rules_likely TEXT,
  foundry_needs TEXT,
  replacement_route TEXT,
  if_succeed TEXT,
  if_fail TEXT,
  if_ignore TEXT,
  if_short TEXT,
  notes TEXT,
  pinned_material JSONB,
  md_path TEXT,
  thread_ids TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW()
);
